// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmzU4bQBFiav3q5Ndn_xl-YdHhYugtP80',
    appId: '1:185991188731:web:15e62c9ed17d869c83a05e',
    messagingSenderId: '185991188731',
    projectId: 'messenger-757b3',
    authDomain: 'messenger-757b3.firebaseapp.com',
    storageBucket: 'messenger-757b3.appspot.com',
    measurementId: 'G-KL7LZ5SRWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyh_9zKFJ6DziWOXCgyKc-j5SVVhmvqU',
    appId: '1:185991188731:android:8d599763c93edf7583a05e',
    messagingSenderId: '185991188731',
    projectId: 'messenger-757b3',
    storageBucket: 'messenger-757b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPzKzcr3-nlXlC5CRdQAwCUUb7eqm0oyY',
    appId: '1:185991188731:ios:f68592c303d2880a83a05e',
    messagingSenderId: '185991188731',
    projectId: 'messenger-757b3',
    storageBucket: 'messenger-757b3.appspot.com',
    iosClientId: '185991188731-bt6jue2bt0jugg92crke7abbdn2516bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinygram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPzKzcr3-nlXlC5CRdQAwCUUb7eqm0oyY',
    appId: '1:185991188731:ios:f68592c303d2880a83a05e',
    messagingSenderId: '185991188731',
    projectId: 'messenger-757b3',
    storageBucket: 'messenger-757b3.appspot.com',
    iosClientId: '185991188731-bt6jue2bt0jugg92crke7abbdn2516bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinygram',
  );
}
